#!/bin/bash

set -eu

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
swift_dir="$here/../../utf8-swift/swift"
test -d "$swift_dir" || { echo "error: swift not found in '$swift_dir'"; exit 1; }

(
cd "$swift_dir"/..
for dir in compiler-rt llvm swift-xcode-playground-support \
    swift-corelibs-foundation clang llbuild cmark lldb swiftpm \
    swift-corelibs-xctest ninja swift-integration-tests swift \
    swift-corelibs-libdispatch; do
    (
    cd "$dir"
    git fetch > /dev/null
    )
done
)

swift_sha=$(git ls-remote -h git@github.com:milseman/swift.git refs/heads/utf8string | cut -f1)
echo "- swift sha: $swift_sha"

tmpfile=$(mktemp /tmp/.update-checkout_XXXXXX)
cat >> "$tmpfile" <<EOF
{
    "https-clone-pattern": "https://github.com/%s.git",
    "ssh-clone-pattern": "git@github.com:%s.git",
    "repos": {
        "compiler-rt": {
            "remote": {
                "id": "apple/swift-compiler-rt"
            }
        },
        "llvm": {
            "remote": {
                "id": "apple/swift-llvm"
            }
        },
        "swift-xcode-playground-support": {
            "remote": {
                "id": "apple/swift-xcode-playground-support"
            }
        },
        "swift-corelibs-foundation": {
            "remote": {
                "id": "apple/swift-corelibs-foundation"
            }
        },
        "clang": {
            "remote": {
                "id": "apple/swift-clang"
            }
        },
        "llbuild": {
            "remote": {
                "id": "apple/swift-llbuild"
            }
        },
        "cmark": {
            "remote": {
                "id": "apple/swift-cmark"
            }
        },
        "lldb": {
            "remote": {
                "id": "apple/swift-lldb"
            }
        },
        "swift-corelibs-xctest": {
            "remote": {
                "id": "apple/swift-corelibs-xctest"
            }
        },
        "ninja": {
            "remote": {
                "id": "ninja-build/ninja"
            }
        },
        "swift-integration-tests": {
            "remote": {
                "id": "apple/swift-integration-tests"
            }
        },
        "swiftpm": {
            "remote": {
                "id": "apple/swift-package-manager"
            }
        },
        "swift": {
            "remote": {
                "id": "apple/swift"
            }
        },
        "swift-corelibs-libdispatch": {
            "remote": {
                "id": "apple/swift-corelibs-libdispatch"
            }
        }
    },
    "branch-schemes": {
        "utf8string": {
            "repos": {
                "compiler-rt": "a658fd1cb262e409dcb0650f7818c0277a5f81a4",
                "llvm": "c4295e5d5d274deea47f4d8b22b19562a2516511",
                "swift-xcode-playground-support": "6bf092e51bf23dd42e130d84d553e38c80aefdc0",
                "swift-corelibs-foundation": "68c074949329f41290aca9ed13e64a53e5426932",
                "clang": "babfefb6b5123c3d6bb3651a4a02548eaca90045",
                "llbuild": "7a639c283de367a42ad5bce3d934e20de0628546",
                "cmark": "b00c889eb66d38cb8f37847efef89aeca4e4b520",
                "lldb": "2bde84223ec637fb27575ef48f7207eb3d95585f",
                "swift-syntax": "bbdb60c4d1a41dc0cf9bd9ea36379ba6e6b71f82",
                "swiftpm": "106115d356f750223dbd4419c3f39f8fc2da66f7",
                "swift-corelibs-xctest": "b27fd5f97d04b6c2bbf0011efa976ba373e417e8",
                "ninja": "253e94c1fa511704baeb61cf69995bbf09ba435e",
                "swift-integration-tests": "6cfcfc91fa986a82588680bbcd011eacaaf1400b",
                "swift": "$swift_sha",
                "swift-corelibs-libdispatch": "6162a1d17948502cbe0576058d19e095ef3ad8c7"
            },
            "aliases": [
                "utf8string"
            ]
        }
    }
}
EOF

(
cd "$swift_dir"
utils/update-checkout --config="$tmpfile" --scheme=utf8string
)

rm "$tmpfile"

echo OK
